### ISSUE TITLE
Extension doesn't work anymore

### ISSUE THREAD

**Issue by NatoBoram** [jbockle/format-files#23]
When I try to format a folder or a workspace, I instantly get this message.

![image](https://user-images.githubusercontent.com/10495562/114953676-e00fa680-9e26-11eb-91de-dfbd4331dbe5.png)

```yaml
Version: 1.56.0-insider
Commit: 25785b97e533b15ae3b12e48aaf4187416437e62
Date: 2021-04-15T05:14:21.699Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
